name: cued-fc
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - setuptools
  - numpy==1.26.4
  - scipy
  - matplotlib
  - pandas
  - ipython
  - ipywidgets
  - ipykernel
  - jupyter
  - seaborn
  - pip:      
    - pyserial==3.5
    - tqdm==4.66.1
    - PyQt6
    - requests
    - reportlab
    - gspread
    - oauth2client
    - gspread-dataframe
    - python-dotenv
