# this environment file does not work for Windows.
name: cued-fc
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip
  - python=3.8
  - setuptools
  - pandas
  - numpy 
  - arduino-cli=0.35.3
  - pip:      
      - pyserial==3.5
      - tqdm==4.66.1
      - PyQt6==6.6.1
