name: cued-fc
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip
  - python=3.8
  - setuptools
  - numpy 
  - pip:      
    - pyserial==3.5
    - tqdm==4.66.1
    - PyQt6
    - requests
    - reportlab
    - pandas
    - matplotlib
