SKETCH_PATH = "Software/Rig/Rig.ino"
PARAMS_PATH = "Software/Rig/trial.h"

NO_PUFF_NEGATIVE = 'no_puff_CS-'
PUFF_POSITIVE = 'puff_CS+'
NO_PUFF_POSITIVE = 'no_puff_CS+'
PUFF_NEGATIVE = 'puff_CS-'
TRIAL_CLASSES = [NO_PUFF_NEGATIVE, PUFF_POSITIVE, NO_PUFF_POSITIVE, PUFF_NEGATIVE]
