SKETCH_PATH = "Software/Rig/Rig.ino"
PARAMS_PATH = "Software/Rig/trial.h"
START_STRING = "Session has started"

NO_PUFF_NEGATIVE = 'no_puff_CS-'
PUFF_POSITIVE = 'puff_CS+'
NO_PUFF_POSITIVE = 'no_puff_CS+'
PUFF_NEGATIVE = 'puff_CS-'
NO_PUFF_NO_SIGNAL = 'no_puff_no_signal'
TRIAL_CLASSES = [NO_PUFF_NEGATIVE, PUFF_POSITIVE, NO_PUFF_POSITIVE, PUFF_NEGATIVE, NO_PUFF_NO_SIGNAL]
