SKETCH_PATH = "Software/Rig/Rig.ino"
PARAMS_PATH = "Software/Rig/trial.h"
START_STRING = "Session has started"

NO_TRAINING_NEGATIVE = 'no_training_CS-'
TRAINING_POSITIVE = 'training_CS+'
NO_TRAINING_POSITIVE = 'no_training_CS+'
TRAINING_NEGATIVE = 'training_CS-'
NO_TRAINING_NO_SIGNAL = 'no_training_no_signal'
TRIAL_CLASSES = [NO_TRAINING_NEGATIVE, TRAINING_POSITIVE, NO_TRAINING_POSITIVE, TRAINING_NEGATIVE, NO_TRAINING_NO_SIGNAL]
