---
name: Run Python Analysis Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # As of November 2024, Google Colab runs on Python 3.10, but we
        # can test one version back and two ahead to be more sure that
        # the tests are compatible with Colab
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd Analysis/
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd Analysis/
          python -m unittest discover -s tfcrig/tests
